[project]
title = "Preswald Project"
version = "0.1.0"
port = 8501
entrypoint = "hello.py"

[branding]
name = "Preswald Project"
logo = "images/logo.png"
favicon = "images/favicon.ico"
primaryColor = "#F89613"

[data.earthquake_data]
type = "csv"
path = "data/earthquake_data.csv"
delimiter = ","
header = true
