[project]
title = "Preswald Project"
version = "0.1.0"
port = 8501
slug = "api-341888"  # Required: Unique identifier for your project
entrypoint = "nasa.py"    # Required: Main script to run when executing preswald run

[branding]
name = "Preswald Project"
logo = "static/assets/logo.png"
favicon = "static/assets/favicon.ico"
primaryColor = "#F89613"

[data.sample_csv]
type = "csv"
path = "data/sample.csv"

[data.jsonplaceholder_api]
type = "api"
url = "https://jsonplaceholder.typicode.com/posts"
method = "GET"
response_format = "json"

[data.nasa_apod]
type = "api"
url = "https://api.nasa.gov/planetary/apod"
method = "GET"
params = { "api_key" = "EP2N5vkxlD8R50Fmybj3xyYCat3BTXhxFAwo4sF7"}


[logging]
level = "INFO"  # Options: DEBUG, INFO, WARNING, ERROR, CRITICAL
format = "%(asctime)s - %(name)s - %(levelname)s - %(message)s"