[project]
title = "Water Consumption Project"
version = "0.1.0"
port = 8501
slug = "demo-project-429709"  # Required: Unique identifier for your project
entrypoint = "hello.py"    # Required: Main script to run when executing preswald run

[branding]
name = "Water Consumption"
logo = "images/logo.png"
favicon = "images/favicon.ico"
primaryColor = "#F89613"

[data.global_water_consumption_csv]
type = "csv"
path = "data/global_water_consumption.csv"

[logging]
level = "INFO"  # Options: DEBUG, INFO, WARNING, ERROR, CRITICAL
format = "%(asctime)s - %(name)s - %(levelname)s - %(message)s"