# Add your secrets here (DO NOT commit this file)

[data.postgres]
password = ""

[data.mysql]
password = ""

[data.json]
api_key = ""  # API key for JSON endpoint
                    
[logging]
level = "INFO"  # Options: DEBUG, INFO, WARNING, ERROR, CRITICAL
format = "%(asctime)s - %(name)s - %(levelname)s - %(message)s"
