[project]
title = "Startup Data Analysis"
version = "0.1.0"
port = 8501
slug = "startup-data-analysis-768210"
entrypoint = "index.py"
description = "An interactive dashboard for analyzing startup data"

[branding]
name = "Startup Data Analysis"
logo = "images/logo.png"
favicon = "images/favicon.ico"
primaryColor = "#F89613"

[data.startup_data_csv]
type = "csv"
path = "data/startup_data.csv"

[logging]
level = "INFO"
format = "%(asctime)s - %(name)s - %(levelname)s - %(message)s"

[dependencies]
preswald = ">=0.1.0"
plotly = ">=5.3.1"
pandas = ">=1.3.3"