[project]
title = "Real Estate Prices | Preswald"
version = "0.1.0"
port = 8501

[branding]
name = "Real Estate Prices"
logo = "images/logo.png"
favicon = "images/favicon.ico"
primaryColor = "#FFA500"

[logging]
level = "INFO"  # Options: DEBUG, INFO, WARNING, ERROR, CRITICAL
format = "%(asctime)s - %(name)s - %(levelname)s - %(message)s"

[data.csv]
type = "csv"
path = "real_estate.csv"
delimiter = ","
header = true