[project]
title = "Preswald Tutorial"
version = "0.1.0"
port = 8501
entrypoint = "hello.py"
slug = "preswald-tutorial"

[branding]
name = "Preswald Tutorial"
logo = "images/logo.png"
favicon = "images/favicon.ico"
primaryColor = "#000000"

[data.sample_csv]
type = "csv"
path = "data/sample.csv"
# encoding = "latin-1"  # Uncomment and set to "latin-1" for ISO-8859-1 encoded files

[logging]
level = "INFO"  # Options: DEBUG, INFO, WARNING, ERROR, CRITICAL
format = "%(asctime)s - %(name)s - %(levelname)s - %(message)s"
