[project]
title = "Manoj Assessment"
version = "0.1.0"
port = 8501
slug = "pokemon-383896"  # Required: Unique identifier for your project
entrypoint = "hello.py"    # Required: Main script to run when executing preswald run

[branding]
name = "Manoj Assessment"
logo = "images/logo.png"
favicon = "images/favicon.ico"
primaryColor = "#CC0000"

[data.pokemon_data]
type = "csv"
path = "data/pokemon.csv"

[logging]
level = "INFO"  # Options: DEBUG, INFO, WARNING, ERROR, CRITICAL
format = "%(asctime)s - %(name)s - %(levelname)s - %(message)s"