[project]
title = "Pokedex Project"
version = "0.1.0"
port = 8501
slug = "preswald-pokemon-000001"  # Required: Unique identifier for your project
entrypoint = "main.py"    # Required: Main script to run when executing preswald run

[branding]
name = "Pokedex Project"
logo = "images/logo-pokedex.png"
favicon = "images/favicon.ico"
primaryColor = "#F89613"

[data.pokedex_csv]
type = "csv"
path = "data/pokedex.csv"

[logging]
level = "INFO"  # Options: DEBUG, INFO, WARNING, ERROR, CRITICAL
format = "%(asctime)s - %(name)s - %(levelname)s - %(message)s"
