[project]
title = "Pokemon Dashboard"
version = "0.1.0"
port = 8501
slug = "amruth-pokemon-dashboard"  # Required: Unique identifier for your project
entrypoint = "pokemon_dashboard.py"    # Required: Main script to run when executing preswald run

[branding]
name = "Pokemon Dashboard"
logo = "images/pika.png"
favicon = "images/favicon.ico"
primaryColor = "#F89613"

[data.pokedex_csv]
type = "csv"
path = "data/pokedex.csv"

[logging]
level = "INFO"  # Options: DEBUG, INFO, WARNING, ERROR, CRITICAL
format = "%(asctime)s - %(name)s - %(levelname)s - %(message)s"