# Add your secrets here (DO NOT commit this file)

[connections.postgres_main]
password = ""  # PostgreSQL password

[connections.mysql_main]
password = ""  # MySQL password

[connections.api_data]
api_key = ""  # API key for JSON endpoint
