[project]
title = "Preswald Project"
version = "0.1.0"
port = 8501
slug = "my-example-project-111445"  # Required: Unique identifier for your project
entrypoint = "hello.py"    # Required: Main script to run when executing preswald run

[branding]
name = "Preswald Project"
logo = "images/logo.png"
favicon = "images/favicon.ico"
primaryColor = "#F89613"

[data.districts]
type = "csv"
path = "data/districts.csv"

[data.states]
type = "csv"
path = "data/states.csv"

[data.naep]
type = "csv"
path = "data/naep.csv"

[logging]
level = "INFO"  # Options: DEBUG, INFO, WARNING, ERROR, CRITICAL
format = "%(asctime)s - %(name)s - %(levelname)s - %(message)s"