[project]
title = "Automobile Sales Viz - EDA"
version = "0.1.0"
port = 8501
slug = "automobile-sales-191063"  # Required: Unique identifier for your project
entrypoint = "hello.py"    # Required: Main script to run when executing preswald run

[branding]
name = "Automobile Sales Viz - EDA"
logo = "images/logo.png"
favicon = "images/favicon.ico"
primaryColor = "#F89613"

[data.auto_sales_data]
type = "csv"
path = "data/auto_sales_data.csv"

[logging]
level = "INFO"  # Options: DEBUG, INFO, WARNING, ERROR, CRITICAL
format = "%(asctime)s - %(name)s - %(levelname)s - %(message)s"