[project]
title = "Preswald Project"
version = "0.1.0"
port = 8501
slug = "brics-economic-data"  # Required: Unique identifier for your project
entrypoint = "hello.py"    # Required: Main script to run when executing preswald run

[branding]
name = "BRICS Economic Data"
logo = "images/logo.png"
favicon = "images/favicon.ico"
primaryColor = "#F89613"

[data.economic_data]
type = "csv"
path = "data/BRICS Economic Data.csv"

[logging]
level = "INFO"  # Options: DEBUG, INFO, WARNING, ERROR, CRITICAL
format = "%(asctime)s - %(name)s - %(levelname)s - %(message)s"