[project]
title = "AMZN Stock Magic by Anantjyot Grang"
version = "0.1.0"
port = 8501
slug = "anantjyot-project-387536"  # Required: Unique identifier for your project
entrypoint = "hello.py"    # Required: Main script to run when executing preswald run

[branding]
name = "AMZN Stock Magic by Anantjyot Grang"
logo = "images/logo.png"
favicon = "images/favicon.ico"
primaryColor = "#117abf"


[data.amzn_csv]
type = "csv"
path = "data/AMZN_stock_data.csv"

[logging]
level = "INFO"  # Options: DEBUG, INFO, WARNING, ERROR, CRITICAL
format = "%(asctime)s - %(name)s - %(levelname)s - %(message)s"