[project]
title = "Spotify Analysis"
version = "0.1.0"
port = 8501
slug = "spotify-analysis-779668"  # Required: Unique identifier for your project
entrypoint = "hello.py"    # Required: Main script to run when executing preswald run

[branding]
name = "Spotify Analysis"
logo = "images/logo.png"
favicon = "images/favicon.ico"
primaryColor = "#F89613"

[data.songs_csv]
type = "csv"
path = "data/songs.csv"

[logging]
level = "INFO"  # Options: DEBUG, INFO, WARNING, ERROR, CRITICAL
format = "%(asctime)s - %(name)s - %(levelname)s - %(message)s"