[project]
title = "Preswald Project"
version = "0.1.0"
port = 8501
slug = "weather-app-181709"
entrypoint = "hello.py"

[branding]
name = "Preswald Project"
logo = "images/logo.png"
favicon = "images/favicon.ico"
primaryColor = "#F89613"

[data.weather]  # Changed from sample_csv to weather
type = "csv"
path = "data/weather.csv"

[logging]
level = "INFO"
format = "%(asctime)s - %(name)s - %(levelname)s - %(message)s"
