[project]
title = "Preswald Project"
version = "0.1.0"
port = 8501
slug = "my-project-240162"  # Required: Unique identifier for your project
entrypoint = "LACrimeReport.py"    # Required: Main script to run when executing preswald run


[branding]
name = "Preswald Project"
logo = "images/logo.png"
favicon = "images/favicon.ico"
primaryColor = "#F89613"

[data.LACrimeReport_csv]
type = "csv"
path = "data/LACrimeReportSmall.csv"

[logging]
level = "INFO"  # Options: DEBUG, INFO, WARNING, ERROR, CRITICAL
format = "%(asctime)s - %(name)s - %(levelname)s - %(message)s"